version: '3'
services:
  cert_builder:
    image: cert-builder
    build: cert_builder/.
    volumes: 
      - certs-volume:/certs

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - certs-volume:/etc/nginx/certs/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - echo
      - python_server
    networks:
      - nginx_network
    depends_on:
      - cert_builder

  echo:
    image: "mendhak/http-https-echo"
    expose:
      - 443
    networks:
      - nginx_network

  python_server:
    build: .
    volumes:
      - ./python_server/src:/app/src
      - certs-volume:/app/certs/
    expose: 
      - 5000
    networks:
      - nginx_network
    depends_on:
      - cert_builder
  
  python_client:
    build: .
    volumes:
      - ./python_client/src:/app/src
      - certs-volume:/app/certs/
    networks:
      - nginx_network
    depends_on:
      - cert_builder
      - nginx
      - python_server
      - echo

networks:
  nginx_network:
    driver: bridge

volumes:
  certs-volume: