version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - echo
      - python_server
    networks:
      - nginx_network

  echo:
    image: "mendhak/http-https-echo"
    expose:
      - 443
    networks:
      - nginx_network

  python_server:
    build: .
    volumes:
      - ./certs:/app/certs/
    expose: 
      - 5000
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

